### ISSUE TITLE
Model Type Analysis

### ISSUE THREAD

**Issue by NevinJulian** [Davee02/HSLU.DSPRO1.BirdDetection#11]

**Comment by Davee02** [comment]
Closing this as we decided to use the following models:
- Random baseline
- Single fine-tuned CNN as more complex baseline
- Fine-tuned OpenAI Whisper (based on [this paper](https://www.isca-archive.org/interspeech_2024/sheikh24_interspeech.html))
- Multifeature Fusion and Transformer Encoder (based on [this paper](https://www.mdpi.com/1424-8220/23/19/8099))
